// Radhe Sweets - Comprehensive Seed Data & Store Schema

export const initialData = {
  shopInfo: {
    name: "Radhe Sweets",
    subName: "SWEETS & MORE",
    motto: "Sweet Moments With Radhe Krishna",
    owner: "Admin (AS)",
    phone: "+91 98765 43210",
    email: "contact@radhesweets.com",
    address: "Shop No. 12-14, Shivalik Plaza, IIM Road, Ahmedabad, Gujarat 380015",
    gstin: "24AAACR1234F1Z8",
    fssai: "10721026000452",
    upiId: "radhesweets@oksbi",
    currency: "₹",
    date: "25 Sep 2026"
  },

  branches: [
    { id: "br-1", code: "BR-NAV-01", name: "Navrangpura Flagship", city: "Ahmedabad", revenue: 42850, orders: 126, margin: "34.1%" },
    { id: "br-2", code: "BR-SAT-02", name: "Satellite Luxury Boutique", city: "Ahmedabad", revenue: 31400, orders: 88, margin: "36.5%" },
    { id: "br-3", code: "BR-SGH-03", name: "SG Highway Central Kitchen", city: "Ahmedabad", revenue: 58200, orders: 174, margin: "31.8%" }
  ],
  parkedBills: [
    { id: "park-1", label: "Token #14 (Mr. Patel)", time: "10:15 AM", itemsCount: 2, total: 360, items: [
      { name: "Kaju Katli", qty: 0.5, unit: "kg", rate: 450, total: 225 },
      { name: "Special Punjabi Samosa", qty: 3, unit: "pcs", rate: 45, total: 135 }
    ]}
  ],

  rawMaterials: [
    { id: "rm-1", name: "Whole Goan Cashews (W320)", stock: 85, unit: "kg", unitCost: 250, reorderLevel: 25, expiry: "15 Dec 2026", isPerishable: false },
    { id: "rm-2", name: "Fresh Mawa / Khoya", stock: 18, unit: "kg", unitCost: 120, reorderLevel: 20, expiry: "28 Sep 2026", isPerishable: true },
    { id: "rm-3", name: "Fresh Paneer / Chhena", stock: 12, unit: "kg", unitCost: 180, reorderLevel: 15, expiry: "27 Sep 2026", isPerishable: true },
    { id: "rm-4", name: "Shuddh Desi Ghee (Bilona)", stock: 140, unit: "kg", unitCost: 620, reorderLevel: 40, expiry: "30 Mar 2027", isPerishable: false },
    { id: "rm-5", name: "Double Sulphur Sugar", stock: 210, unit: "kg", unitCost: 42, reorderLevel: 50, expiry: "10 Jan 2027", isPerishable: false },
    { id: "rm-6", name: "Kashmiri Mongra Saffron", stock: 120, unit: "grams", unitCost: 220, reorderLevel: 30, expiry: "20 May 2027", isPerishable: false },
    { id: "rm-7", name: "Eco Sweet Box (1kg Gold Emboss)", stock: 650, unit: "boxes", unitCost: 18, reorderLevel: 100, expiry: "N/A", isPerishable: false },
    { id: "rm-8", name: "Eco Sweet Box (500g)", stock: 820, unit: "boxes", unitCost: 12, reorderLevel: 150, expiry: "N/A", isPerishable: false }
  ],

  advanceOrders: [
    {
      id: "ADV-2026-001",
      customerName: "Patel Family Wedding",
      customerPhone: "+91 98765 67890",
      eventDate: "05 Oct 2026",
      eventType: "Wedding Catering",
      itemsSummary: "50kg Kaju Katli, 50kg Motichoor Ladoo (Pure Ghee)",
      totalAmount: 30500,
      depositPaid: 15000,
      balanceDue: 15500,
      status: "Confirmed"
    },
    {
      id: "ADV-2026-002",
      customerName: "Reliance Petro Corporate Gifting",
      customerPhone: "+91 98765 12345",
      eventDate: "12 Oct 2026",
      eventType: "Corporate Festival Hampers",
      itemsSummary: "120 Artisanal Dry Fruit Sweet Boxes (1kg each)",
      totalAmount: 54000,
      depositPaid: 54000,
      balanceDue: 0,
      status: "Completed"
    },
    {
      id: "ADV-2026-003",
      customerName: "Mehta Griha Pravesh",
      customerPhone: "+91 98765 43210",
      eventDate: "18 Oct 2026",
      eventType: "House Warming",
      itemsSummary: "20kg Dry Fruit Barfi, 10kg Kesar Peda",
      totalAmount: 12200,
      depositPaid: 5000,
      balanceDue: 7200,
      status: "Confirmed"
    }
  ],

  zReports: [
    {
      id: "ZR-20260925-01",
      shift: "Morning Counter Shift (08:00 AM - 02:00 PM)",
      cashier: "Anand Shah (AS)",
      openingFloat: 5000,
      expectedCash: 18450,
      countedCash: 18450,
      variance: 0,
      upiTotal: 14200,
      cardTotal: 6200,
      totalSales: 38850,
      status: "Balanced"
    }
  ],

  auditLogs: [
    { time: "10:28 AM", user: "Admin (AS)", action: "Bill Settled", details: "Order #SA00129 created for ₹565 (Cash)" },
    { time: "10:15 AM", user: "Admin (AS)", action: "Bill Parked", details: "Parked bill Token #14 (Patel) during counter rush" },
    { time: "09:40 AM", user: "Head Chef", action: "Batch Logged", details: "Fresh batch recorded: 10kg Kaju Katli (Consumed 7kg Cashews, 3.5kg Sugar)" },
    { time: "08:00 AM", user: "Admin (AS)", action: "Drawer Opened", details: "Opening cash float verified: ₹5,000" }
  ],

  kpis: {
    customers: { value: 184, change: "+12% today", isUp: true, sub: "today" },
    sales: { value: 42850, change: "+8.4%", isUp: true, formatted: "₹42,850" },
    orders: { value: 126, change: "+9.2%", isUp: true, formatted: "126" },
    profit: { value: 14620, change: "34.1% margin", isUp: true, formatted: "₹14,620" },
    cost: { value: 28230, change: "65.9%", isUp: false, formatted: "₹28,230" },
    returning: { value: 76, change: "+41.3%", isUp: true, formatted: "76", sub: "customers" }
  },

  orderStatusCounts: {
    completed: 94,
    advance: 22,
    kitchen: 10,
    total: 126
  },

  salesOverview: [
    { day: "1 Sep", amount: 14500 },
    { day: "5 Sep", amount: 21000 },
    { day: "10 Sep", amount: 18500 },
    { day: "15 Sep", amount: 32000 },
    { day: "20 Sep", amount: 28000 },
    { day: "25 Sep", amount: 42850 },
    { day: "30 Sep", amount: 48000 }
  ],

  categories: ["All", "Kaju & Dry Fruit", "Ladoo", "Barfi & Peda", "Bengali & Chhena", "Desi Ghee & Fried", "Halwa", "Traditional & Milk", "Traditional & Flaky", "Traditional & Ghee", "Mawa & Khoya", "Beverages"],

  sweets: [
    {
        "id": "sw-1",
        "num": 1,
        "name": "Kaju Katli",
        "tagline": "Cashew & Silver Vark",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 900,
        "costPrice": 540,
        "grossMargin": "40.0%",
        "stock": 15,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "KK",
        "description": "Diamond-shaped rich Goan cashew fudge layered with pure edible silver vark.",
        "gridCol": 0,
        "gridRow": 0,
        "gridPosX": "0.00",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-2",
        "num": 2,
        "name": "Gulab Jamun",
        "tagline": "Mawa Sweet",
        "category": "Mawa & Khoya",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 22,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "GJ",
        "description": "Golden fried khoya dumplings soaked in warm rose petal & cardamom sugar nectar.",
        "gridCol": 1,
        "gridRow": 0,
        "gridPosX": "11.11",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-3",
        "num": 3,
        "name": "Rasgulla",
        "tagline": "Fresh Chhena",
        "category": "Bengali & Chhena",
        "pricePerKg": 340,
        "costPrice": 204,
        "grossMargin": "40.0%",
        "stock": 29,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "R",
        "description": "Tender, spongy fresh cottage cheese chhena dumplings soaked in delicate cardamom syrup.",
        "gridCol": 2,
        "gridRow": 0,
        "gridPosX": "22.22",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-4",
        "num": 4,
        "name": "Rasmalai",
        "tagline": "Saffron Clotted Milk",
        "category": "Bengali & Chhena",
        "pricePerKg": 480,
        "costPrice": 288,
        "grossMargin": "40.0%",
        "stock": 36,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "R",
        "description": "Soft flattened chhena patties steeped in chilled saffron and pistachio flavored rich milk.",
        "gridCol": 3,
        "gridRow": 0,
        "gridPosX": "33.33",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-5",
        "num": 5,
        "name": "Jalebi",
        "tagline": "Desi Ghee Spiral",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 43,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "J",
        "description": "Crispy pretzel-shaped spirals fried in pure desi ghee, soaked in piping hot sugar syrup.",
        "gridCol": 4,
        "gridRow": 0,
        "gridPosX": "44.44",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-6",
        "num": 6,
        "name": "Motichoor Ladoo",
        "tagline": "Desi Ghee Pearls",
        "category": "Ladoo",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 50,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "ML",
        "description": "Melt-in-mouth tiny besan pearls fried in pure Shuddh Desi Ghee with melon seeds.",
        "gridCol": 5,
        "gridRow": 0,
        "gridPosX": "55.56",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-7",
        "num": 7,
        "name": "Besan Ladoo",
        "tagline": "Roasted Gram Flour",
        "category": "Ladoo",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 57,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "BL",
        "description": "Traditional aromatic roasted besan balls laced with desi ghee and fragrant green cardamom.",
        "gridCol": 6,
        "gridRow": 0,
        "gridPosX": "66.67",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-8",
        "num": 8,
        "name": "Soan Papdi",
        "tagline": "Crisp & Flaky",
        "category": "Traditional & Flaky",
        "pricePerKg": 300,
        "costPrice": 180,
        "grossMargin": "40.0%",
        "stock": 64,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "SP",
        "description": "Crisp, flaky, and layered traditional sweet confection that dissolves effortlessly on your tongue.",
        "gridCol": 7,
        "gridRow": 0,
        "gridPosX": "77.78",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-9",
        "num": 9,
        "name": "Peda",
        "tagline": "Mathura Style",
        "category": "Barfi & Peda",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 71,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "P",
        "description": "Semi-soft golden milk fudge infused with roasted cardamom and crushed pistachio.",
        "gridCol": 8,
        "gridRow": 0,
        "gridPosX": "88.89",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-10",
        "num": 10,
        "name": "Barfi",
        "tagline": "Pure Mawa Fudge",
        "category": "Barfi & Peda",
        "pricePerKg": 400,
        "costPrice": 240,
        "grossMargin": "40.0%",
        "stock": 78,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Best Seller",
        "code": "B",
        "description": "Classic rich condensed milk fudge cut into neat diamond squares.",
        "gridCol": 9,
        "gridRow": 0,
        "gridPosX": "100.00",
        "gridPosY": "0.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-11",
        "num": 11,
        "name": "Kesar Pista Roll",
        "tagline": "Saffron Pistachio",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 960,
        "costPrice": 576,
        "grossMargin": "40.0%",
        "stock": 20,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KP",
        "description": "Exquisite hand-rolled cashew cylinder stuffed with pistachios and Kashmiri saffron.",
        "gridCol": 0,
        "gridRow": 1,
        "gridPosX": "0.00",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-12",
        "num": 12,
        "name": "Kalakand",
        "tagline": "Granular Milk Cake",
        "category": "Mawa & Khoya",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 27,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "K",
        "description": "Moist, soft and granular traditional milk sweet topped with sliced almonds.",
        "gridCol": 1,
        "gridRow": 1,
        "gridPosX": "11.11",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-13",
        "num": 13,
        "name": "Cham Cham",
        "tagline": "Bengali Chhena Sweet",
        "category": "Bengali & Chhena",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 34,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CC",
        "description": "Oval-shaped cottage cheese delicacy garnished with mawa crumble and saffron syrup.",
        "gridCol": 2,
        "gridRow": 1,
        "gridPosX": "22.22",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-14",
        "num": 14,
        "name": "Malpua",
        "tagline": "Fried Sweet Pancake",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 41,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "M",
        "description": "Crispy edged sweet pancakes dipped in cardamom scented syrup, served warm.",
        "gridCol": 3,
        "gridRow": 1,
        "gridPosX": "33.33",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-15",
        "num": 15,
        "name": "Ghevar",
        "tagline": "Rajasthani Honeycomb",
        "category": "Traditional & Flaky",
        "pricePerKg": 580,
        "costPrice": 348,
        "grossMargin": "40.0%",
        "stock": 48,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "G",
        "description": "Disc-shaped honeycomb sweet pastry soaked in sugar syrup and topped with rich rabri.",
        "gridCol": 4,
        "gridRow": 1,
        "gridPosX": "44.44",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-16",
        "num": 16,
        "name": "Imarti",
        "tagline": "Flower Shaped Jalebi",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 55,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "I",
        "description": "Intricately spun urad dal batter fried in pure ghee with deep orange floral glaze.",
        "gridCol": 5,
        "gridRow": 1,
        "gridPosX": "55.56",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-17",
        "num": 17,
        "name": "Laddu (Boondi)",
        "tagline": "Juicy Sweet Boondi",
        "category": "Ladoo",
        "pricePerKg": 340,
        "costPrice": 204,
        "grossMargin": "40.0%",
        "stock": 62,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "L(",
        "description": "Larger golden boondi pearls packed with cashews, raisins, and aromatic cloves.",
        "gridCol": 6,
        "gridRow": 1,
        "gridPosX": "66.67",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-18",
        "num": 18,
        "name": "Balushahi",
        "tagline": "Flaky Glazed Pastry",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 69,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "B",
        "description": "Traditional flaky doughnut-like pastry with crisp exterior and soft syrup center.",
        "gridCol": 7,
        "gridRow": 1,
        "gridPosX": "77.78",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-19",
        "num": 19,
        "name": "Mawa Kachori",
        "tagline": "Jodhpur Royal Sweet",
        "category": "Traditional & Flaky",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 76,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MK",
        "description": "Crisp puffed kachori stuffed with rich dry fruit mawa and soaked in sugar syrup.",
        "gridCol": 8,
        "gridRow": 1,
        "gridPosX": "88.89",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-20",
        "num": 20,
        "name": "Chandrakala",
        "tagline": "Crescent Moon Sweet",
        "category": "Mawa & Khoya",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 18,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "C",
        "description": "Crescent-shaped crimped sweet pastry filled with rich khoya, coconut, and nuts.",
        "gridCol": 9,
        "gridRow": 1,
        "gridPosX": "100.00",
        "gridPosY": "11.11",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-21",
        "num": 21,
        "name": "Shrikhand",
        "tagline": "Kesar Elaichi Curd",
        "category": "Bengali & Chhena",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 25,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "S",
        "description": "Silky strained yogurt dessert whipped with saffron threads, cardamom, and nuts.",
        "gridCol": 0,
        "gridRow": 2,
        "gridPosX": "0.00",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-22",
        "num": 22,
        "name": "Basundi",
        "tagline": "Thick Sweet Milk",
        "category": "Traditional & Milk",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 32,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "B",
        "description": "Slow-reduced rich milk flavored with cardamom, nutmeg, charoli seeds and saffron.",
        "gridCol": 1,
        "gridRow": 2,
        "gridPosX": "11.11",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-23",
        "num": 23,
        "name": "Rabri",
        "tagline": "Lachhadar Malai",
        "category": "Traditional & Milk",
        "pricePerKg": 400,
        "costPrice": 240,
        "grossMargin": "40.0%",
        "stock": 39,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "R",
        "description": "Creamy layered clotted cream ribbons soaked in thickened sweetened whole milk.",
        "gridCol": 2,
        "gridRow": 2,
        "gridPosX": "22.22",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-24",
        "num": 24,
        "name": "Kheer",
        "tagline": "Rice & Cardamom",
        "category": "Traditional & Milk",
        "pricePerKg": 260,
        "costPrice": 156,
        "grossMargin": "40.0%",
        "stock": 46,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "K",
        "description": "Traditional slow-simmered basmati rice pudding infused with saffron and dry fruits.",
        "gridCol": 3,
        "gridRow": 2,
        "gridPosX": "33.33",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-25",
        "num": 25,
        "name": "Phirni",
        "tagline": "Clay Pot Ground Rice",
        "category": "Traditional & Milk",
        "pricePerKg": 280,
        "costPrice": 168,
        "grossMargin": "40.0%",
        "stock": 53,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "P",
        "description": "Creamy ground rice pudding chilled in earthy clay earthenware bowls (matkas).",
        "gridCol": 4,
        "gridRow": 2,
        "gridPosX": "44.44",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-26",
        "num": 26,
        "name": "Kulfi",
        "tagline": "Malai Matka Kulfi",
        "category": "Traditional & Milk",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 60,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "K",
        "description": "Dense, creamy traditional Indian ice cream flavored with pistachio and saffron.",
        "gridCol": 5,
        "gridRow": 2,
        "gridPosX": "55.56",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-27",
        "num": 27,
        "name": "Falooda",
        "tagline": "Rose & Basil Seeds",
        "category": "Beverages",
        "pricePerKg": 220,
        "costPrice": 132,
        "grossMargin": "40.0%",
        "stock": 67,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "F",
        "description": "Chilled rose milk layered with vermicelli falooda noodles, sabja seeds, and kulfi.",
        "gridCol": 6,
        "gridRow": 2,
        "gridPosX": "66.67",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-28",
        "num": 28,
        "name": "Angoori Petha",
        "tagline": "Agra Ash Gourd",
        "category": "Traditional & Flaky",
        "pricePerKg": 260,
        "costPrice": 156,
        "grossMargin": "40.0%",
        "stock": 74,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "AP",
        "description": "Translucent bite-sized ash gourd grape jewels simmered in pure sugar syrup.",
        "gridCol": 7,
        "gridRow": 2,
        "gridPosX": "77.78",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-29",
        "num": 29,
        "name": "Kaju Pista Roll",
        "tagline": "Dual Nut Roll",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 980,
        "costPrice": 588,
        "grossMargin": "40.0%",
        "stock": 16,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "KP",
        "description": "Dual colored cylindrical rolls of premium cashews wrapped around Iranian pistachios.",
        "gridCol": 8,
        "gridRow": 2,
        "gridPosX": "88.89",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-30",
        "num": 30,
        "name": "Dry Fruit Barfi",
        "tagline": "Sugarfree Dates & Fig",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 850,
        "costPrice": 510,
        "grossMargin": "40.0%",
        "stock": 23,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "DF",
        "description": "Artisanal natural sugar-free sweet made with dates, figs, almonds, cashews, and pistachios.",
        "gridCol": 9,
        "gridRow": 2,
        "gridPosX": "100.00",
        "gridPosY": "22.22",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-31",
        "num": 31,
        "name": "Sandesh",
        "tagline": "Kolkata Special",
        "category": "Bengali & Chhena",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 30,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "S",
        "description": "Delicate melt-in-mouth Bengali sweet prepared from fresh kneaded cottage cheese.",
        "gridCol": 0,
        "gridRow": 3,
        "gridPosX": "0.00",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-32",
        "num": 32,
        "name": "Mishti Doi",
        "tagline": "Caramelized Sweet Curd",
        "category": "Bengali & Chhena",
        "pricePerKg": 240,
        "costPrice": 144,
        "grossMargin": "40.0%",
        "stock": 37,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MD",
        "description": "Famous Bengali sweetened yogurt fermented to perfection in traditional earthen pots.",
        "gridCol": 1,
        "gridRow": 3,
        "gridPosX": "11.11",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-33",
        "num": 33,
        "name": "Chhena Poda",
        "tagline": "Baked Cottage Cheese",
        "category": "Bengali & Chhena",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 44,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CP",
        "description": "Odisha's signature caramelized roasted chhena cake with a golden burnt crust.",
        "gridCol": 2,
        "gridRow": 3,
        "gridPosX": "22.22",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-34",
        "num": 34,
        "name": "Gajar Halwa",
        "tagline": "Red Delhi Carrots",
        "category": "Halwa",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 51,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "GH",
        "description": "Slow cooked winter red carrots in pure desi ghee, khoya, and crunchy dry fruits.",
        "gridCol": 3,
        "gridRow": 3,
        "gridPosX": "33.33",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-35",
        "num": 35,
        "name": "Moong Dal Halwa",
        "tagline": "Shuddh Ghee Moong",
        "category": "Halwa",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 58,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MD",
        "description": "Royal Rajasthani golden yellow lentil halwa roasted patiently in Shuddh Desi Ghee.",
        "gridCol": 4,
        "gridRow": 3,
        "gridPosX": "44.44",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-36",
        "num": 36,
        "name": "Atta Halwa",
        "tagline": "Kada Prasad Style",
        "category": "Halwa",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 65,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "AH",
        "description": "Rich and wholesome whole wheat halwa made with equal parts ghee, flour, and sugar.",
        "gridCol": 5,
        "gridRow": 3,
        "gridPosX": "55.56",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-37",
        "num": 37,
        "name": "Suji Halwa",
        "tagline": "Rava Sheera",
        "category": "Halwa",
        "pricePerKg": 280,
        "costPrice": 168,
        "grossMargin": "40.0%",
        "stock": 72,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "SH",
        "description": "Golden semolina halwa with aromatic cardamom, roasted cashews, and raisins.",
        "gridCol": 6,
        "gridRow": 3,
        "gridPosX": "66.67",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-38",
        "num": 38,
        "name": "Sohan Halwa",
        "tagline": "Caramelized Brittle",
        "category": "Halwa",
        "pricePerKg": 520,
        "costPrice": 312,
        "grossMargin": "40.0%",
        "stock": 79,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "SH",
        "description": "Dense, chewy, nutty traditional halwa disks studded with almonds and pistachios.",
        "gridCol": 7,
        "gridRow": 3,
        "gridPosX": "77.78",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-39",
        "num": 39,
        "name": "Dry Fruit Ladoo",
        "tagline": "Nutrient Rich",
        "category": "Ladoo",
        "pricePerKg": 840,
        "costPrice": 504,
        "grossMargin": "40.0%",
        "stock": 21,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "DF",
        "description": "Sugar-free powerhouse ladoo packed with walnuts, cashews, figs, and pumpkin seeds.",
        "gridCol": 8,
        "gridRow": 3,
        "gridPosX": "88.89",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-40",
        "num": 40,
        "name": "Til Ladoo",
        "tagline": "Sesame & Jaggery",
        "category": "Ladoo",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 28,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "TL",
        "description": "Traditional Makar Sankranti roasted white sesame seeds bound with organic jaggery.",
        "gridCol": 9,
        "gridRow": 3,
        "gridPosX": "100.00",
        "gridPosY": "33.33",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-41",
        "num": 41,
        "name": "Nariyal Ladoo",
        "tagline": "Fresh Coconut",
        "category": "Ladoo",
        "pricePerKg": 340,
        "costPrice": 204,
        "grossMargin": "40.0%",
        "stock": 35,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "NL",
        "description": "Soft white ladoos rolled from freshly grated coconut and sweetened condensed milk.",
        "gridCol": 0,
        "gridRow": 4,
        "gridPosX": "0.00",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-42",
        "num": 42,
        "name": "Pinni",
        "tagline": "Punjabi Energy Sweet",
        "category": "Traditional & Ghee",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 42,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "P",
        "description": "Nutritious winter sweet made with wheat flour, desi ghee, almonds, and edible gum.",
        "gridCol": 1,
        "gridRow": 4,
        "gridPosX": "11.11",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-43",
        "num": 43,
        "name": "Chocolate Barfi",
        "tagline": "Dual Chocolate Mawa",
        "category": "Barfi & Peda",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 49,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CB",
        "description": "Kids favorite dual layered fudge combining rich dark cocoa with creamy milk mawa.",
        "gridCol": 2,
        "gridRow": 4,
        "gridPosX": "22.22",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-44",
        "num": 44,
        "name": "Mewa Bati",
        "tagline": "Stuffed Gulab Jamun",
        "category": "Mawa & Khoya",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 56,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MB",
        "description": "Rajasthani specialty khoya dumpling stuffed with dry fruits, fried to deep dark perfection.",
        "gridCol": 3,
        "gridRow": 4,
        "gridPosX": "33.33",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-45",
        "num": 45,
        "name": "Badam Katli",
        "tagline": "California Almond",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 920,
        "costPrice": 552,
        "grossMargin": "40.0%",
        "stock": 63,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "BK",
        "description": "Velvety diamond-shaped fudge crafted entirely from California blanched almonds.",
        "gridCol": 4,
        "gridRow": 4,
        "gridPosX": "44.44",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-46",
        "num": 46,
        "name": "Pista Barfi",
        "tagline": "Emerald Pistachio",
        "category": "Barfi & Peda",
        "pricePerKg": 980,
        "costPrice": 588,
        "grossMargin": "40.0%",
        "stock": 70,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "PB",
        "description": "Vibrant green rich fudge made from stone-ground pistachios and cardamom.",
        "gridCol": 5,
        "gridRow": 4,
        "gridPosX": "55.56",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-47",
        "num": 47,
        "name": "Anjeer Barfi",
        "tagline": "Afghan Figs",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 880,
        "costPrice": 528,
        "grossMargin": "40.0%",
        "stock": 77,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "AB",
        "description": "Chewy and crunchy artisanal barfi made from sun-dried Afghan figs and roasted nuts.",
        "gridCol": 6,
        "gridRow": 4,
        "gridPosX": "66.67",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-48",
        "num": 48,
        "name": "Rose Barfi",
        "tagline": "Damask Rose Petals",
        "category": "Barfi & Peda",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 19,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "RB",
        "description": "Aromatic pink fudge infused with organic Damask rose water and real rose petals.",
        "gridCol": 7,
        "gridRow": 4,
        "gridPosX": "77.78",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-49",
        "num": 49,
        "name": "Mango Barfi",
        "tagline": "Ratnagiri Alphonso",
        "category": "Barfi & Peda",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 26,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MB",
        "description": "Sunny yellow mawa barfi flavored with real Alphonso mango pulp and saffron.",
        "gridCol": 8,
        "gridRow": 4,
        "gridPosX": "88.89",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-50",
        "num": 50,
        "name": "Coconut Barfi",
        "tagline": "Classic Kopra Pak",
        "category": "Barfi & Peda",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 33,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CB",
        "description": "Dual layer white and saffron coconut fudge with a sweet tropical crunch.",
        "gridCol": 9,
        "gridRow": 4,
        "gridPosX": "100.00",
        "gridPosY": "44.44",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-51",
        "num": 51,
        "name": "Chikoo Barfi",
        "tagline": "Sapota Fruit Fudge",
        "category": "Barfi & Peda",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 40,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CB",
        "description": "Unique and natural fruit barfi crafted from ripe Dahanu chikoos and mawa.",
        "gridCol": 0,
        "gridRow": 5,
        "gridPosX": "0.00",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-52",
        "num": 52,
        "name": "Rasakadam",
        "tagline": "Kheer Kadam",
        "category": "Bengali & Chhena",
        "pricePerKg": 480,
        "costPrice": 288,
        "grossMargin": "40.0%",
        "stock": 47,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "R",
        "description": "Exquisite two-in-one sweet: juicy mini rasgulla encased inside soft mawa shell.",
        "gridCol": 1,
        "gridRow": 5,
        "gridPosX": "11.11",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-53",
        "num": 53,
        "name": "Makhana Ladoo",
        "tagline": "Foxnut Superfood",
        "category": "Ladoo",
        "pricePerKg": 640,
        "costPrice": 384,
        "grossMargin": "40.0%",
        "stock": 54,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "ML",
        "description": "Healthy roasted lotus seeds ground with ghee, nuts, and organic jaggery.",
        "gridCol": 2,
        "gridRow": 5,
        "gridPosX": "22.22",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-54",
        "num": 54,
        "name": "Gond Ladoo",
        "tagline": "Edible Gum & Ghee",
        "category": "Ladoo",
        "pricePerKg": 520,
        "costPrice": 312,
        "grossMargin": "40.0%",
        "stock": 61,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "GL",
        "description": "Wholesome traditional postpartum and winter wellness ladoo loaded with dry fruits.",
        "gridCol": 3,
        "gridRow": 5,
        "gridPosX": "33.33",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-55",
        "num": 55,
        "name": "Rajbhog",
        "tagline": "Royal Yellow Rasgulla",
        "category": "Bengali & Chhena",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 68,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "R",
        "description": "Jumbo saffron infused cottage cheese ball stuffed with dry fruits and cardamom.",
        "gridCol": 4,
        "gridRow": 5,
        "gridPosX": "44.44",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-56",
        "num": 56,
        "name": "Malai Peda",
        "tagline": "Creamy Soft Peda",
        "category": "Barfi & Peda",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 75,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MP",
        "description": "Ultra-soft and creamy peda prepared by slow reducing rich buffalo milk.",
        "gridCol": 5,
        "gridRow": 5,
        "gridPosX": "55.56",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-57",
        "num": 57,
        "name": "Lauki Halwa",
        "tagline": "Doodhi Halwa",
        "category": "Halwa",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 17,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "LH",
        "description": "Light and flavorful green bottle gourd halwa braised in milk, ghee, and khoya.",
        "gridCol": 6,
        "gridRow": 5,
        "gridPosX": "66.67",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-58",
        "num": 58,
        "name": "Paan Ladoo",
        "tagline": "Betel Leaf & Gulkand",
        "category": "Ladoo",
        "pricePerKg": 480,
        "costPrice": 288,
        "grossMargin": "40.0%",
        "stock": 24,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "PL",
        "description": "Refreshing emerald coconut balls stuffed with fragrant Kolkata meetha paan gulkand.",
        "gridCol": 7,
        "gridRow": 5,
        "gridPosX": "77.78",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-59",
        "num": 59,
        "name": "Kimami Sewai",
        "tagline": "Awadhi Roasted Vermicelli",
        "category": "Traditional & Ghee",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 31,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KS",
        "description": "Lucknowi festival delicacy of roasted fine vermicelli simmered in rich sugar syrup.",
        "gridCol": 8,
        "gridRow": 5,
        "gridPosX": "88.89",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-60",
        "num": 60,
        "name": "Shahi Tukda",
        "tagline": "Royal Mughlai Dessert",
        "category": "Traditional & Ghee",
        "pricePerKg": 340,
        "costPrice": 204,
        "grossMargin": "40.0%",
        "stock": 38,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "ST",
        "description": "Golden fried bread crisps bathed in thick saffron rabri and sprinkled with pistachios.",
        "gridCol": 9,
        "gridRow": 5,
        "gridPosX": "100.00",
        "gridPosY": "55.56",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-61",
        "num": 61,
        "name": "Rasgulla (Brown)",
        "tagline": "Nolen Gur Special",
        "category": "Bengali & Chhena",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 45,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "R(",
        "description": "Winter special Bengali rasgulla sweetened with aromatic date palm jaggery (nolen gur).",
        "gridCol": 0,
        "gridRow": 6,
        "gridPosX": "0.00",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-62",
        "num": 62,
        "name": "Kala Jamun",
        "tagline": "Dark Caramelized Jamun",
        "category": "Mawa & Khoya",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 52,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KJ",
        "description": "Deep dark fried paneer and khoya balls with a crisp outer crust and soft juicy interior.",
        "gridCol": 1,
        "gridRow": 6,
        "gridPosX": "11.11",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-63",
        "num": 63,
        "name": "Peni",
        "tagline": "Layered Crisp Peni",
        "category": "Traditional & Ghee",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 59,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "P",
        "description": "Feather-light crispy fried layered vermicelli coils dusted with powdered sugar.",
        "gridCol": 2,
        "gridRow": 6,
        "gridPosX": "22.22",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-64",
        "num": 64,
        "name": "Khoya Barfi",
        "tagline": "Plain Milk Fudge",
        "category": "Barfi & Peda",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 66,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KB",
        "description": "Pure reduced milk mawa fudge with clean cardamom aroma and silver garnish.",
        "gridCol": 3,
        "gridRow": 6,
        "gridPosX": "33.33",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-65",
        "num": 65,
        "name": "Singori",
        "tagline": "Molu Leaf Cone",
        "category": "Traditional & Ghee",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 73,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "S",
        "description": "Kumaoni hill station specialty of khoya and coconut wrapped in fresh green leaves.",
        "gridCol": 4,
        "gridRow": 6,
        "gridPosX": "44.44",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-66",
        "num": 66,
        "name": "Moti Pak",
        "tagline": "Besan & Khoya Slice",
        "category": "Barfi & Peda",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 15,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "MP",
        "description": "Rich festive sweet made with tiny boondi pearls set with creamy mawa fudge.",
        "gridCol": 5,
        "gridRow": 6,
        "gridPosX": "55.56",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-67",
        "num": 67,
        "name": "Doodh Peda",
        "tagline": "Pure Cow Milk",
        "category": "Barfi & Peda",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 22,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "DP",
        "description": "Authentic temple-style pale yellow peda made purely with thickened cows milk.",
        "gridCol": 6,
        "gridRow": 6,
        "gridPosX": "66.67",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-68",
        "num": 68,
        "name": "Elaichi Barfi",
        "tagline": "Green Cardamom",
        "category": "Barfi & Peda",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 29,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "EB",
        "description": "Fragrant mawa barfi generously infused with hand-pounded Idukki green cardamom.",
        "gridCol": 7,
        "gridRow": 6,
        "gridPosX": "77.78",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-69",
        "num": 69,
        "name": "Pineapple Pastry",
        "tagline": "Pineapple Halwa Cake",
        "category": "Halwa & Special",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 36,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "PP",
        "description": "Delectable tropical Indian sweet layered with fresh pineapple chunks and mawa.",
        "gridCol": 8,
        "gridRow": 6,
        "gridPosX": "88.89",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-70",
        "num": 70,
        "name": "Chamcham",
        "tagline": "Malai Roll Chamcham",
        "category": "Bengali & Chhena",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 43,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "C",
        "description": "Long cylindrical Bengali chhena sweet filled with sweet cream and rolled in coconut.",
        "gridCol": 9,
        "gridRow": 6,
        "gridPosX": "100.00",
        "gridPosY": "66.67",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-71",
        "num": 71,
        "name": "Besan Barfi",
        "tagline": "Mohanthal Style",
        "category": "Barfi & Peda",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 50,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "BB",
        "description": "Traditional Gujarati style coarse gram flour fudge roasted in aromatic ghee.",
        "gridCol": 0,
        "gridRow": 7,
        "gridPosX": "0.00",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-72",
        "num": 72,
        "name": "Cornflour Halwa",
        "tagline": "Bombay Karachi Halwa",
        "category": "Halwa",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 57,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CH",
        "description": "Translucent chewy jelly-like halwa cubes loaded with crunchy melon seeds and cashews.",
        "gridCol": 1,
        "gridRow": 7,
        "gridPosX": "11.11",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-73",
        "num": 73,
        "name": "Dry Fruit Kachori",
        "tagline": "Sweet Nutty Puffs",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 480,
        "costPrice": 288,
        "grossMargin": "40.0%",
        "stock": 64,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "DF",
        "description": "Crispy sweet kachori balls filled with spiced dry fruits and saffron syrup.",
        "gridCol": 2,
        "gridRow": 7,
        "gridPosX": "22.22",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-74",
        "num": 74,
        "name": "Ghughra",
        "tagline": "Gujarati Karanji",
        "category": "Traditional & Ghee",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 71,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "G",
        "description": "Half-moon shaped golden flaky pastry filled with roasted semolina, coconut, and nuts.",
        "gridCol": 3,
        "gridRow": 7,
        "gridPosX": "33.33",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-75",
        "num": 75,
        "name": "Pethe ki Barfi",
        "tagline": "Ash Gourd Fudge",
        "category": "Traditional & Ghee",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 78,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "PK",
        "description": "Unique fusion of candied white pumpkin pulp and rich khoya milk fudge.",
        "gridCol": 4,
        "gridRow": 7,
        "gridPosX": "44.44",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-76",
        "num": 76,
        "name": "Khopra Pak",
        "tagline": "Saffron Coconut",
        "category": "Barfi & Peda",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 20,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KP",
        "description": "Rich Gujarati coconut cake cooked with milk, mawa, saffron, and nutmeg.",
        "gridCol": 5,
        "gridRow": 7,
        "gridPosX": "55.56",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-77",
        "num": 77,
        "name": "Meethi Mathri",
        "tagline": "Sweet Biscuit",
        "category": "Traditional & Ghee",
        "pricePerKg": 280,
        "costPrice": 168,
        "grossMargin": "40.0%",
        "stock": 27,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MM",
        "description": "Crispy, sweet, flaky flour rounds fried in ghee with subtle fennel seed notes.",
        "gridCol": 6,
        "gridRow": 7,
        "gridPosX": "66.67",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-78",
        "num": 78,
        "name": "Shakkarpara",
        "tagline": "Sugar Glazed Diamond",
        "category": "Traditional & Ghee",
        "pricePerKg": 260,
        "costPrice": 156,
        "grossMargin": "40.0%",
        "stock": 34,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "S",
        "description": "Crisp bite-sized diamond flour cookies coated with crystalline sugar syrup.",
        "gridCol": 7,
        "gridRow": 7,
        "gridPosX": "77.78",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-79",
        "num": 79,
        "name": "Gujiya",
        "tagline": "Holi Festival Special",
        "category": "Traditional & Ghee",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 41,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "G",
        "description": "Crispy deep-fried sweet dumpling stuffed with khoya, dry fruits, and aromatic spices.",
        "gridCol": 8,
        "gridRow": 7,
        "gridPosX": "88.89",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-80",
        "num": 80,
        "name": "Thekua",
        "tagline": "Bihari Chhath Prasad",
        "category": "Traditional & Ghee",
        "pricePerKg": 280,
        "costPrice": 168,
        "grossMargin": "40.0%",
        "stock": 48,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "T",
        "description": "Hard, crispy traditional whole wheat and jaggery cookies stamped with ornate wooden molds.",
        "gridCol": 9,
        "gridRow": 7,
        "gridPosX": "100.00",
        "gridPosY": "77.78",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-81",
        "num": 81,
        "name": "Anarsa",
        "tagline": "Sesame Rice Pastry",
        "category": "Traditional & Ghee",
        "pricePerKg": 340,
        "costPrice": 204,
        "grossMargin": "40.0%",
        "stock": 55,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "A",
        "description": "Fermented rice flour and jaggery patty coated with white sesame, fried in pure ghee.",
        "gridCol": 0,
        "gridRow": 8,
        "gridPosX": "0.00",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-82",
        "num": 82,
        "name": "Puran Poli",
        "tagline": "Sweet Lentil Bread",
        "category": "Traditional & Ghee",
        "pricePerKg": 300,
        "costPrice": 180,
        "grossMargin": "40.0%",
        "stock": 62,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "PP",
        "description": "Warm flatbread stuffed with sweet cooked chana dal, jaggery, cardamom, and nutmeg.",
        "gridCol": 1,
        "gridRow": 8,
        "gridPosX": "11.11",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-83",
        "num": 83,
        "name": "Balu Shahi",
        "tagline": "Crisp Glazed Ring",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 69,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "BS",
        "description": "Flaky concentric rings of refined dough fried slow in ghee and dipped in syrup.",
        "gridCol": 2,
        "gridRow": 8,
        "gridPosX": "22.22",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-84",
        "num": 84,
        "name": "Chena Jalebi",
        "tagline": "Chhena Spun Coil",
        "category": "Bengali & Chhena",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 76,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CJ",
        "description": "Specialty jalebi made from fresh cottage cheese chhena, fried golden with soft juicy bite.",
        "gridCol": 3,
        "gridRow": 8,
        "gridPosX": "33.33",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-85",
        "num": 85,
        "name": "Adhirasam",
        "tagline": "Tamil Deep South Sweet",
        "category": "Traditional & Ghee",
        "pricePerKg": 320,
        "costPrice": 192,
        "grossMargin": "40.0%",
        "stock": 18,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "A",
        "description": "Ancient Tamil pastry made with raw rice flour and spiced jaggery dough.",
        "gridCol": 4,
        "gridRow": 8,
        "gridPosX": "44.44",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-86",
        "num": 86,
        "name": "Mysore Pak",
        "tagline": "Melt-In-Mouth Ghee",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 480,
        "costPrice": 288,
        "grossMargin": "40.0%",
        "stock": 25,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "MP",
        "description": "Iconic South Indian royal sweet made from generous amounts of pure ghee, besan, and sugar.",
        "gridCol": 5,
        "gridRow": 8,
        "gridPosX": "55.56",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-87",
        "num": 87,
        "name": "Dharwad Peda",
        "tagline": "Caramelized Karnataka",
        "category": "Barfi & Peda",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 32,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "DP",
        "description": "Deep brown roasted milk peda rolled in fine castor sugar, with deep caramelized flavor.",
        "gridCol": 6,
        "gridRow": 8,
        "gridPosX": "66.67",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-88",
        "num": 88,
        "name": "Kunda",
        "tagline": "Belgaum Milk Sweet",
        "category": "Traditional & Milk",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 39,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "K",
        "description": "Rich brown caramelized milk dessert slow-cooked until intensely concentrated.",
        "gridCol": 7,
        "gridRow": 8,
        "gridPosX": "77.78",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-89",
        "num": 89,
        "name": "Tilkut",
        "tagline": "Gaya Crushed Sesame",
        "category": "Traditional & Ghee",
        "pricePerKg": 340,
        "costPrice": 204,
        "grossMargin": "40.0%",
        "stock": 46,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "T",
        "description": "Bihari winter sweet of pounded sesame seeds and jaggery with incredible flaky crunch.",
        "gridCol": 8,
        "gridRow": 8,
        "gridPosX": "88.89",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-90",
        "num": 90,
        "name": "Badusha",
        "tagline": "South Indian Balushahi",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 360,
        "costPrice": 216,
        "grossMargin": "40.0%",
        "stock": 53,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "B",
        "description": "Soft, layered, flaky melt-in-mouth pastry topped with cardamom sugar glaze.",
        "gridCol": 9,
        "gridRow": 8,
        "gridPosX": "100.00",
        "gridPosY": "88.89",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-91",
        "num": 91,
        "name": "Jalidar Peda",
        "tagline": "Lattice Pattern Peda",
        "category": "Barfi & Peda",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 60,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "JP",
        "description": "Artistic lattice stamped golden peda infused with pure mawa and saffron essence.",
        "gridCol": 0,
        "gridRow": 9,
        "gridPosX": "0.00",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-92",
        "num": 92,
        "name": "Kesar Barfi",
        "tagline": "Pure Saffron Fudge",
        "category": "Barfi & Peda",
        "pricePerKg": 480,
        "costPrice": 288,
        "grossMargin": "40.0%",
        "stock": 67,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KB",
        "description": "Rich golden-yellow mawa barfi studded with real saffron threads and silver foil.",
        "gridCol": 1,
        "gridRow": 9,
        "gridPosX": "11.11",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-93",
        "num": 93,
        "name": "Chhena Murki",
        "tagline": "Candied Chhena Cubes",
        "category": "Bengali & Chhena",
        "pricePerKg": 420,
        "costPrice": 252,
        "grossMargin": "40.0%",
        "stock": 74,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "CM",
        "description": "Small firm cubes of fresh cottage cheese coated in a crisp crystalline sugar shell.",
        "gridCol": 2,
        "gridRow": 9,
        "gridPosX": "22.22",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-94",
        "num": 94,
        "name": "Mango Peda",
        "tagline": "Fresh Mango Khoya",
        "category": "Barfi & Peda",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 16,
        "unit": "kg",
        "stockStatus": "Low Stock",
        "badge": "Low Stock",
        "code": "MP",
        "description": "Tangy-sweet fruit peda crafted from fresh Alphonso mango pulp and milk mawa.",
        "gridCol": 3,
        "gridRow": 9,
        "gridPosX": "33.33",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-95",
        "num": 95,
        "name": "Litchi Burfi",
        "tagline": "Shahi Litchi Pulp",
        "category": "Barfi & Peda",
        "pricePerKg": 460,
        "costPrice": 276,
        "grossMargin": "40.0%",
        "stock": 23,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "LB",
        "description": "Delicate white barfi flavored with aromatic Shahi litchi fruit and subtle rose.",
        "gridCol": 4,
        "gridRow": 9,
        "gridPosX": "44.44",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-96",
        "num": 96,
        "name": "Kaju Anjeer Roll",
        "tagline": "Cashew & Fig Cylinder",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 980,
        "costPrice": 588,
        "grossMargin": "40.0%",
        "stock": 30,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KA",
        "description": "Exquisite two-toned cylinder: outer rich cashew fudge wrapping spiced Afghan fig paste.",
        "gridCol": 5,
        "gridRow": 9,
        "gridPosX": "55.56",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-97",
        "num": 97,
        "name": "Nutty Bites",
        "tagline": "Roasted Almonds & Cashews",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 880,
        "costPrice": 528,
        "grossMargin": "40.0%",
        "stock": 37,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "NB",
        "description": "Crunchy square cubes of slow roasted almonds, cashews, and pistachios bound with honey.",
        "gridCol": 6,
        "gridRow": 9,
        "gridPosX": "66.67",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-98",
        "num": 98,
        "name": "Rabri Malpua",
        "tagline": "Malpua with Rabri",
        "category": "Desi Ghee & Fried",
        "pricePerKg": 440,
        "costPrice": 264,
        "grossMargin": "40.0%",
        "stock": 44,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "RM",
        "description": "Crispy fried malpuas drenched in sweet syrup, served alongside chilled thick lachha rabri.",
        "gridCol": 7,
        "gridRow": 9,
        "gridPosX": "77.78",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-99",
        "num": 99,
        "name": "Dry Fruit Roll",
        "tagline": "Four Nut Medley",
        "category": "Kaju & Dry Fruit",
        "pricePerKg": 960,
        "costPrice": 576,
        "grossMargin": "40.0%",
        "stock": 51,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "DF",
        "description": "Artisanal roll packed with roasted almonds, pistachios, cashews, and golden raisins.",
        "gridCol": 8,
        "gridRow": 9,
        "gridPosX": "88.89",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    },
    {
        "id": "sw-100",
        "num": 100,
        "name": "Kesar Rasgulla",
        "tagline": "Saffron Infused Chhena",
        "category": "Bengali & Chhena",
        "pricePerKg": 380,
        "costPrice": 228,
        "grossMargin": "40.0%",
        "stock": 58,
        "unit": "kg",
        "stockStatus": "In Stock",
        "badge": "Fresh Batch",
        "code": "KR",
        "description": "Golden yellow spongy chhena balls simmered in fragrant saffron and cardamom sugar nectar.",
        "gridCol": 9,
        "gridRow": 9,
        "gridPosX": "100.00",
        "gridPosY": "100.00",
        "image": "./assets/100_mithais_grid.png",
        "fallbackImage": "./assets/100_mithais_grid.png"
    }
],

  customers: [
    {
      id: "cust-1",
      name: "Jignesh Shah",
      phone: "+91 98765 67890",
      email: "jignesh@gmail.com",
      address: "B-402, Samruddhi Heights, Satellite, Ahmedabad, Gujarat",
      type: "VIP",
      tier: "VIP",
      loyaltyPoints: 420,
      khataBalance: 1250,
      creditLimit: 10000,
      totalOrders: 28,
      totalSpent: 8450,
      notes: "Preferred customer. Prefers low-sugar sweets and extra silver vark."
    },
    {
      id: "cust-2",
      name: "Riya Patel",
      phone: "+91 98765 43210",
      email: "riya@gmail.com",
      address: "12, Shanti Niketan, Alkapuri, Vadodara, Gujarat",
      type: "Regular",
      tier: "Regular",
      loyaltyPoints: 85,
      khataBalance: 0,
      creditLimit: 5000,
      totalOrders: 3,
      totalSpent: 1250,
      notes: "Likes fresh hot Gulab Jamun for family dinners."
    },
    {
      id: "cust-3",
      name: "Amit Kumar",
      phone: "+91 98765 12345",
      email: "amit@gmail.com",
      address: "78, Ring Road, Vesu, Surat, Gujarat",
      type: "Regular",
      tier: "Regular",
      loyaltyPoints: 310,
      khataBalance: 4200,
      creditLimit: 15000,
      totalOrders: 12,
      totalSpent: 4320,
      notes: "Frequent corporate bulk order buyer."
    },
    {
      id: "cust-4",
      name: "Priya Panchal",
      phone: "+91 98765 11122",
      email: "priya@gmail.com",
      address: "301, Pushpak Flats, Vastrapur, Ahmedabad",
      type: "Regular",
      tier: "Regular",
      loyaltyPoints: 160,
      khataBalance: 0,
      creditLimit: 5000,
      totalOrders: 7,
      totalSpent: 2890,
      notes: "Always requests gift box packaging."
    },
    {
      id: "cust-5",
      name: "Neha Shah",
      phone: "+91 98765 77665",
      email: "neha@gmail.com",
      address: "Sector 21, Gandhinagar, Gujarat",
      type: "Regular",
      tier: "Regular",
      loyaltyPoints: 215,
      khataBalance: 850,
      creditLimit: 7500,
      totalOrders: 9,
      totalSpent: 3410,
      notes: "Regular weekend sweets purchaser."
    },
    {
      id: "cust-6",
      name: "Meet Kothari",
      phone: "+91 98765 99887",
      email: "meet@gmail.com",
      address: "55, Navrangpura, Ahmedabad",
      type: "New",
      tier: "New",
      loyaltyPoints: 30,
      khataBalance: 0,
      creditLimit: 2000,
      totalOrders: 2,
      totalSpent: 780,
      notes: "New customer from online search."
    },
    {
      id: "cust-7",
      name: "Rakesh Thakkar",
      phone: "+91 98765 11223",
      email: "rakesh@gmail.com",
      address: "Kalawad Road, Rajkot, Gujarat",
      type: "Regular",
      tier: "Regular",
      loyaltyPoints: 140,
      khataBalance: 0,
      creditLimit: 5000,
      totalOrders: 5,
      totalSpent: 1950,
      notes: "Prefers Dry Fruit Barfi & Motichoor Ladoo."
    }
  ],

  orders: [
    {
      id: "SA00129",
      date: "25 Sep 2026, 10:28 AM",
      customerId: "cust-1",
      customerName: "Jignesh Shah",
      customerPhone: "+91 98765 67890",
      customerAddress: "Ahmedabad, Gujarat",
      itemsCount: 3,
      total: 565,
      subtotal: 565,
      discount: 0,
      tax: 0,
      paymentMethod: "Cash",
      status: "Completed",
      notes: "Special packing for festival gifting.",
      items: [
        { name: "Kaju Katli", quantity: 0.5, unit: "kg", rate: 450, total: 225 },
        { name: "Gulab Jamun", quantity: 1, unit: "kg", rate: 180, total: 180 },
        { name: "Motichoor Ladoo", quantity: 1, unit: "kg", rate: 160, total: 160 }
      ]
    },
    {
      id: "SA00128",
      date: "25 Sep 2026, 10:15 AM",
      customerId: "cust-2",
      customerName: "Riya Patel",
      customerPhone: "+91 98765 43210",
      customerAddress: "Vadodara, Gujarat",
      itemsCount: 3,
      total: 450,
      subtotal: 450,
      discount: 0,
      tax: 0,
      paymentMethod: "UPI",
      status: "Completed",
      notes: "Immediate counter delivery.",
      items: [
        { name: "Kaju Katli", quantity: 1, unit: "kg", rate: 450, total: 450 }
      ]
    },
    {
      id: "SA00127",
      date: "24 Sep 2026, 7:30 PM",
      customerId: "cust-3",
      customerName: "Amit Kumar",
      customerPhone: "+91 98765 12345",
      customerAddress: "Surat, Gujarat",
      itemsCount: 4,
      total: 320,
      subtotal: 320,
      discount: 0,
      tax: 0,
      paymentMethod: "Cash",
      status: "Advance Booking",
      notes: "Advance festival booking for 8 PM pickup.",
      items: [
        { name: "Rasgulla", quantity: 1, unit: "kg", rate: 320, total: 320 }
      ]
    },
    {
      id: "SA00126",
      date: "24 Sep 2026, 5:10 PM",
      customerId: "cust-4",
      customerName: "Priya Panchal",
      customerPhone: "+91 98765 11122",
      customerAddress: "Ahmedabad, Gujarat",
      itemsCount: 8,
      total: 620,
      subtotal: 620,
      discount: 0,
      tax: 0,
      paymentMethod: "Card",
      status: "Completed",
      notes: "Corporate anniversary celebration.",
      items: [
        { name: "Dry Fruit Barfi", quantity: 1, unit: "kg", rate: 420, total: 420 },
        { name: "Soan Papdi", quantity: 1, unit: "kg", rate: 200, total: 200 }
      ]
    },
    {
      id: "SA00125",
      date: "23 Sep 2026, 2:45 PM",
      customerId: "cust-5",
      customerName: "Neha Shah",
      customerPhone: "+91 98765 77665",
      customerAddress: "Gandhinagar, Gujarat",
      itemsCount: 3,
      total: 290,
      subtotal: 290,
      discount: 0,
      tax: 0,
      paymentMethod: "UPI",
      status: "Kitchen Packing",
      notes: "Custom packaging for gift box.",
      items: [
        { name: "Motichoor Ladoo", quantity: 1, unit: "kg", rate: 160, total: 160 },
        { name: "Gulab Jamun", quantity: 0.5, unit: "kg", rate: 180, total: 90 },
        { name: "Special Punjabi Samosa", quantity: 2, unit: "pcs", rate: 20, total: 40 }
      ]
    }
  ],

  expenses: {
    total: 28230,
    change: "+5.6% from last month",
    breakdown: [
      { category: "Raw Materials", amount: 12450, percentage: 44.1, color: "#C86D3B" },
      { category: "Utilities", amount: 5320, percentage: 18.8, color: "#DDA15E" },
      { category: "Staff Salary", amount: 6000, percentage: 21.3, color: "#10B981" },
      { category: "Marketing", amount: 2460, percentage: 8.7, color: "#0284C7" },
      { category: "Other", amount: 2000, percentage: 7.1, color: "#8B5CF6" }
    ],
    items: [
      { id: "exp-1", date: "25 Sep", description: "Raw Materials Purchase (Pure Ghee & Mawa)", category: "Raw Materials", amount: 12450, status: "Paid" },
      { id: "exp-2", date: "22 Sep", description: "Utilities (Electricity & Commercial Gas)", category: "Utilities", amount: 5320, status: "Paid" },
      { id: "exp-3", date: "20 Sep", description: "Staff Salary (Kitchen Halwai & Counter Staff)", category: "Staff Salary", amount: 6000, status: "Paid" },
      { id: "exp-4", date: "18 Sep", description: "Marketing & Festive Banners", category: "Marketing", amount: 2460, status: "Paid" },
      { id: "exp-5", date: "15 Sep", description: "Eco Sweet Packaging Boxes & Bags", category: "Other", amount: 2000, status: "Paid" }
    ]
  },

  analytics: {
    salesByChannel: {
      onlineOrders: { amount: 18240, percentage: 42.6 },
      storeOrders: { amount: 24610, percentage: 57.4 }
    },
    avgOrderValue: 340,
    avgOrderChange: "+5.1%",
    totalOrdersCount: 126,
    ordersGrowth: "+9.2%"
  }
};
